services:
  doh-server:
    image: snowy68/nginx-mainline:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80/tcp"
    volumes:
      - ./nginx:/etc/nginx
      - /etc/passwd:/etc/passwd:ro 